### PR TITLE
Improvements/better hud

### PR DESCRIPTION
**Pull request by AndrzejRyl**

### CODE REVIEW

**Comment by AndrzejRyl** [comment]
In here we have entire new game navigation. Including timer, all menus (Start/Pause/Finish) and NFC button handling.

**Comment by Tifts** [comment]
1. Merge conflicts.
2. The menu requires some more visible selector, maybe highlight the button as well?
3. How about removing/hiding highscores if we don't have them implemented? ;p
4. Could menu be somehow usable in Unity editor as well? Doing 3. might help that.
5. Switching camera is now problematic. I was thinking, that switching cameras on NFC button wasn't a bad idea for now. Player could choose between bots if he has trouble catching one. I wouldn't make it autochangeable for now. But it needs to change somehow, because before changing I got 2fps, and after changing it works fine. How about no pausing (for now)?

**Comment by AndrzejRyl** [comment]
In order to use menu in editor you have to uncheck Gaze Module script from EventSystem and check that one above it ;)

**Comment by AndrzejRyl** [comment]
1. Done
2. Done
3. Done
4. As I said, you have to make this change in EventSystem
5. While crying because of removing my sweet PauseMenu, I did it ;)

**Pull request merged**
